import type { ArchitectureProposal } from "../schemas/architecture.js";

export function generateCdkStack(proposal: ArchitectureProposal): string {
  const serviceNames = proposal.services.map((s) => s.data.service);
  const hasVpc = serviceNames.some((s) => s.toLowerCase().includes("vpc"));
  const hasS3 = serviceNames.some((s) => s.toLowerCase().includes("s3"));
  const hasLambda = serviceNames.some((s) => s.toLowerCase().includes("lambda"));
  const hasDynamoDb = serviceNames.some((s) => s.toLowerCase().includes("dynamodb"));
  const hasApiGateway = serviceNames.some((s) => s.toLowerCase().includes("api gateway"));
  const hasSqs = serviceNames.some((s) => s.toLowerCase().includes("sqs"));
  const hasKms = serviceNames.some((s) => s.toLowerCase().includes("kms"));
  const hasCloudWatch = serviceNames.some((s) => s.toLowerCase().includes("cloudwatch"));

  return `import * as cdk from "aws-cdk-lib";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as apigatewayv2 from "aws-cdk-lib/aws-apigatewayv2";
import * as sqs from "aws-cdk-lib/aws-sqs";
import * as kms from "aws-cdk-lib/aws-kms";
import * as logs from "aws-cdk-lib/aws-logs";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as iam from "aws-cdk-lib/aws-iam";
import { HttpLambdaIntegration } from "aws-cdk-lib/aws-apigatewayv2-integrations";
import { SqsEventSource } from "aws-cdk-lib/aws-lambda-event-sources";
import { Construct } from "constructs";

export interface ${toPascalCase(proposal.projectId)}StackProps extends cdk.StackProps {
  environmentName?: string;
}

/**
 * Generated by CloudArch Architect
 * Project: ${proposal.projectId}
 * Summary: ${proposal.summary.replace(/"/g, '\\"')}
 * Compliance: ${proposal.compliance.framework} ${proposal.compliance.level}
 */
export class ${toPascalCase(proposal.projectId)}Stack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: ${toPascalCase(proposal.projectId)}StackProps) {
    super(scope, id, props);

    const envName = props?.environmentName ?? "prod";

    ${hasKms ? `const encryptionKey = new kms.Key(this, "EncryptionKey", {
      enableKeyRotation: true,
      alias: \`\${envName}-cloudarch-key\`,
      description: "Customer-managed key for ${proposal.compliance.framework} workload",
    });` : ""}

    ${hasVpc ? `const vpc = new ec2.Vpc(this, "Vpc", {
      maxAzs: 2,
      natGateways: 1,
      subnetConfiguration: [
        { name: "Public", subnetType: ec2.SubnetType.PUBLIC },
        { name: "Private", subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      ],
    });` : ""}

    ${hasS3 ? `const documentsBucket = new s3.Bucket(this, "DocumentsBucket", {
      encryption: s3.BucketEncryption.KMS,
      ${hasKms ? "encryptionKey," : ""}
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      versioned: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });` : ""}

    ${hasDynamoDb ? `const metadataTable = new dynamodb.Table(this, "MetadataTable", {
      partitionKey: { name: "documentId", type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      ${hasKms ? "encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED, encryptionKey," : "encryption: dynamodb.TableEncryption.AWS_MANAGED,"}
      pointInTimeRecovery: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });` : ""}

    ${hasSqs ? `const processingQueue = new sqs.Queue(this, "ProcessingQueue", {
      encryption: sqs.QueueEncryption.KMS,
      ${hasKms ? "encryptionMasterKey: encryptionKey," : ""}
      visibilityTimeout: cdk.Duration.seconds(300),
    });` : ""}

    ${hasLambda ? `const processorFn = new lambda.Function(this, "DocumentProcessor", {
      runtime: lambda.Runtime.NODEJS_20_X,
      handler: "index.handler",
      code: lambda.Code.fromInline("exports.handler = async () => ({ statusCode: 200 });"),
      timeout: cdk.Duration.seconds(30),
      ${hasVpc ? "vpc," : ""}
      environment: {
        ${hasS3 ? "BUCKET_NAME: documentsBucket.bucketName," : ""}
        ${hasDynamoDb ? "TABLE_NAME: metadataTable.tableName," : ""}
        ${hasSqs ? "QUEUE_URL: processingQueue.queueUrl," : ""}
      },
    });

    ${hasS3 ? "documentsBucket.grantReadWrite(processorFn);" : ""}
    ${hasDynamoDb ? "metadataTable.grantReadWriteData(processorFn);" : ""}
    ${hasSqs ? `processingQueue.grantConsumeMessages(processorFn);
    processorFn.addEventSource(new SqsEventSource(processingQueue, { batchSize: 10 }));` : ""}` : ""}

    ${hasApiGateway && hasLambda ? `const httpApi = new apigatewayv2.HttpApi(this, "IntakeApi", {
      apiName: \`\${envName}-intake-api\`,
    });

    httpApi.addRoutes({
      path: "/documents",
      methods: [apigatewayv2.HttpMethod.POST],
      integration: new HttpLambdaIntegration("IntakeIntegration", processorFn),
    });` : ""}

    ${hasCloudWatch ? `new logs.LogGroup(this, "ApplicationLogs", {
      retention: logs.RetentionDays.ONE_YEAR,
      ${hasKms ? "encryptionKey," : ""}
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });` : ""}

    new cdk.CfnOutput(this, "ComplianceFramework", {
      value: "${proposal.compliance.framework}",
      description: "Target compliance framework",
    });
  }
}
`;
}

export function generateDeployScript(projectId: string): string {
  return `#!/usr/bin/env bash
set -euo pipefail

# CloudArch Architect — Deploy Script
# Project: ${projectId}
# Region: us-gov-west-1 (AWS GovCloud)

PROFILE="\${AWS_PROFILE:-govcloud}"
REGION="\${AWS_REGION:-us-gov-west-1}"
ACCOUNT=$(aws sts get-caller-identity --profile "$PROFILE" --query Account --output text)

echo "Deploying to GovCloud account $ACCOUNT in $REGION..."

cd "$(dirname "$0")/../infra"

npm install
npm run build

# Bootstrap CDK (first time only)
npx cdk bootstrap "aws://$ACCOUNT/$REGION" --profile "$PROFILE"

# Deploy stack
npx cdk deploy --all --profile "$PROFILE" --require-approval never

echo "Deployment complete."
`;
}

export function generateReadme(proposal: ArchitectureProposal): string {
  return `# ${proposal.projectId} — AWS GovCloud Deployment

${proposal.summary}

## Compliance
- **Framework:** ${proposal.compliance.framework} (${proposal.compliance.level})
- **Region:** us-gov-west-1

## Architecture Overview
${proposal.services.map((s) => `- **${s.data.label}** (${s.data.service}): ${s.data.description ?? s.data.category}`).join("\n")}

## Prerequisites
1. AWS GovCloud account with admin access
2. AWS CLI v2 configured with \`govcloud\` profile
3. Node.js 20+
4. AWS CDK CLI (\`npm install -g aws-cdk\`)

## Deploy Steps
\`\`\`bash
export AWS_PROFILE=govcloud
export AWS_REGION=us-gov-west-1
chmod +x scripts/deploy.sh
./scripts/deploy.sh
\`\`\`

## Cost Estimate
- **Monthly range:** $${proposal.costEstimate.monthlyTotalLow.toFixed(2)} – $${proposal.costEstimate.monthlyTotalHigh.toFixed(2)}
- Verify with [AWS Pricing Calculator](https://calculator.aws/)

## Generated by CloudArch Architect
Paste \`COPILOT_PROMPT.md\` into Cursor or GitHub Copilot to extend this stack with your application logic.
`;
}

export function generateCopilotPrompt(proposal: ArchitectureProposal): string {
  return `# Copilot Prompt — ${proposal.projectId}

You are extending a generated AWS GovCloud CDK stack for the following workload:

**Problem:** ${proposal.summary}

**Compliance:** ${proposal.compliance.framework} ${proposal.compliance.level}

**Services in architecture:**
${proposal.services.map((s) => `- ${s.data.service}: ${s.data.label}`).join("\n")}

**Your tasks:**
1. Review \`infra/lib/stack.ts\` and add business logic for document intake/processing
2. Implement Lambda handler code in a \`src/\` directory
3. Add input validation and error handling for the API endpoints
4. Ensure all resources use KMS encryption and enforce TLS
5. Add CloudWatch alarms for error rates and queue depth
6. Create a GitHub Actions workflow for CI/CD to GovCloud (manual approval gate)
7. Run \`./scripts/deploy.sh\` after \`cdk synth\` passes

**Constraints:**
- Must deploy to us-gov-west-1 only
- No commercial AWS services
- Follow least-privilege IAM
- Include comments explaining each resource for learning purposes
`;
}

export function generateFullIac(proposal: ArchitectureProposal) {
  return {
    cdk: generateCdkStack(proposal),
    deployScript: generateDeployScript(proposal.projectId),
    readme: generateReadme(proposal),
    copilotPrompt: generateCopilotPrompt(proposal),
  };
}

function toPascalCase(str: string): string {
  return replaceNonAlpha(str)
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("") || "Workload";
}

function replaceNonAlpha(str: string): string {
  return str.replace(/[^a-zA-Z0-9-_ ]/g, "");
}
